name: Publish

on:
  push:
    tags:
      - "*"
    branches-ignore:
      - "*"

jobs:

  publish:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        scala: [ 3.1.1 ]
        java: [ graalvm-ce-java17@21.3.0 ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Setup GPG
        run: |
          echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --batch --import
          gpg --list-keys
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
      - name: Publish
        run: sbt +test +publishSigned sonatypeBundleRelease
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
