name: Test

on: [workflow_dispatch,push,pull_request]

jobs:

  build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        scala: [ 3.1.1 ]
        java: [ graalvm-ce-java17@21.3.0 ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Compile and test
        run: sbt +test scalafmtCheckAll
